apiVersion: v1
kind: Service
metadata:
  labels:
    myapp: app
  name: python-web-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31500
  selector:
    myapp: app
  type: NodePort
status:
  loadBalancer: {}

